Use red color for prd accounts
moia-oss/aws-cfg-generator pull request #35
Opened 2021-12-17 07:38 UTC by johannes-gehrs

2021-12-17 09:10 UTC, bemica requested changes
Could you also update this section of the documentation with the new help dialogue? https://github.com/moia-oss/aws-cfg-generator#flags-1

Otherwise looks good!

2022-01-18 10:24 UTC, johannes-gehrs commented
Missed your request for changes, pls take another look

2022-01-18 12:12 UTC, msiuts approved these changes

2022-01-18 12:29 UTC, bemica approved these changes

2022-01-19 08:14 UTC, merged